Create patch set 3
Change has been successfully rebased and submitted as 69d4dfa946cce73ae62dc7e531b4cef0a5acbc42

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: ociregistry/ocimem/check_test.go
Insertions: 2, Deletions: 2.

@@ -90,14 +90,14 @@
 	},
 	wantError: `invalid manifest: manifest for manifests\[0\] not found`,
 }, {
-	testName: "LaxReferences_NonExistentReference",
+	testName: "LaxChildReferences_NonExistentReference",
 	preload: ocitest.RepoContent{
 		Blobs: map[string]string{
 			"a": "{}",
 		},
 	},
 	config: Config{
-		LaxReferences: true,
+		LaxChildReferences: true,
 	},
 	mediaType: ocispec.MediaTypeImageManifest,
 	manifestData: func(content ocitest.PushedRepoContent) []byte {
```
```
The name of the file: ociregistry/ocimem/registry.go
Insertions: 6, Deletions: 4.

@@ -90,10 +90,12 @@
 	// refers to (TODO: not implemented yet)
 	ImmutableTags bool
 
-	// By default, the ocimem implementation checks that
-	// references are present when manifests are uploaded.
-	// Setting LaxReferences to true disables these checks.
-	LaxReferences bool
+	// LaxChildReferences causes the usual child reference checks made
+	// by ocimem to be skipped. This includes references to blobs by
+	// manifests and by manifests (indexes) to other manifests, but not
+	// subject references, because the spec defines those to be always
+	// lax.
+	LaxChildReferences bool
 }
 
 func (r *Registry) repo(repoName string) (*repository, error) {
```
```
The name of the file: ociregistry/ocimem/writer.go
Insertions: 1, Deletions: 1.

@@ -153,7 +153,7 @@
 		// TODO decide what to do about errUnknownManifestMediaTypeForIteration
 		return manifestInfo{}, err
 	}
-	if r.cfg.LaxReferences {
+	if r.cfg.LaxChildReferences {
 		return info, nil
 	}
 	repo, err := r.repo(repoName)
```


Patch-set: 3
Patch-set-description: Rebase
Subject: ocimem: implement LaxChildReferences
Status: merged
Commit: 69d4dfa946cce73ae62dc7e531b4cef0a5acbc42
Tag: autogenerated:gerrit:merged
Groups: 68acd02c8529d2d127c6b006ed433f7334cebea0
Label: Code-Review=+2, 7cde2bf0504302fbd4eacb0d9bb28cb7560c8030 Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, ea0c6408b45193bb0bc185d0d62d6f51fcf546da Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, 0e93ddcd0f3a64a38e753434316465ed5af24a3b
Submission-id: 1218348
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: TryBot-Result: Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Ours: 4d9e2933ef3d306c7526b2f8a4f45d5799c4a405
Theirs: fbfe57b16f62cebfe9d6c2d7fe8e9d43988a7e2c
Contains-Conflicts: false
Attention: {"person_ident":"Gerrit User 1020341 \u003c1020341@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}